files:
  - C:\Users\*\AppData\Roaming\Microsoft\Windows\PowerShell\PSReadLine\ConsoleHost_history.txt
  - C:\Users\*\Downloads\*.txt
  - C:\Users\*\Downloads\*.csv
  - C:\Users\*\Downloads\*.json
registry:
  - HKLM:\SOFTWARE\Microsoft\Windows Defender\Exclusions\Paths
  - HKLM:\SOFTWARE\Microsoft\Windows Defender\Exclusions\Processes
  - HKCU:\Software\Microsoft\Windows\CurrentVersion\Run
